- pom.xml
- src/main/java/org/springframework/samples/petclinic/configuration/EmailConfig.java
- src/main/java/org/springframework/samples/petclinic/model/Anuncio.java
- src/main/java/org/springframework/samples/petclinic/model/Encargo.java
- src/main/java/org/springframework/samples/petclinic/model/Estado.java
- src/main/java/org/springframework/samples/petclinic/model/Portfolio.java
- src/main/java/org/springframework/samples/petclinic/model/Solicitud.java
- src/main/java/org/springframework/samples/petclinic/model/Valoracion.java
- src/main/java/org/springframework/samples/petclinic/repository/BeaverRepository.java
- src/main/java/org/springframework/samples/petclinic/repository/EncargoRepository.java
- src/main/java/org/springframework/samples/petclinic/repository/SolicitudRepository.java
- src/main/java/org/springframework/samples/petclinic/service/BeaverService.java
- src/main/java/org/springframework/samples/petclinic/service/EncargoService.java
- src/main/java/org/springframework/samples/petclinic/service/SolicitudService.java
- src/main/java/org/springframework/samples/petclinic/service/UserService.java
- src/main/java/org/springframework/samples/petclinic/web/EmailSender.java
- src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
- src/main/resources/application.properties
- src/main/webapp/WEB-INF/jsp/testview.jsp
- src/test/java/org/springframework/samples/petclinic/service/BeaverServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/SolicitudServiceTests.java
- src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Que incluye este pull request:
- Aceptar Solicitudes de Encargo (Controlador y Servicio) [Servicio testeado con BBDD y Controlador con Mock]
- Rechazar Solicitudes de Encargo (Controlador y Servicio) [Servicio testeado con BBDD y Controlador con Mock]
- Servicio de Envío de Emails (No completo, necesita algunos cambios) [No testeado]
- Algunos servicios de apoyo: No todos están testeados, consultar coverage de jacoco para más información.
Anotaciones a tener en cuenta:
- Los métodos de apoyo en gran medida seguramente hayan sido desarrollados en otros casos de uso, emplear los que mejor coverage tengan.
- No todas las asociaciones están bien en las entidades, proceder consultando el UML a la hora de revisar.
> CU-013 Aceptar Rechazar Solicitudes de Encargo Backend

- src/main/java/org/springframework/samples/petclinic/service/EncargoService.java
- src/test/java/org/springframework/samples/petclinic/model/AnuncioValidatorTests.java
- src/test/java/org/springframework/samples/petclinic/model/EncargoValidatorTest.java
- src/test/java/org/springframework/samples/petclinic/service/EncargoServiceTests.java
Se añaden los test de Servicios de la entidad Encargo a la rama general de los casos de uso relacionados con esta entidad
> Encargo service tests

- src/main/webapp/WEB-INF/jsp/welcome.jsp
- src/main/webapp/WEB-INF/tags/footer.tag
- src/main/webapp/WEB-INF/tags/menu.tag
Added footer.
Added button 'sobre nosotros' with link to the landing page.
Added a new welcome page.
> Welcome changes

- src/main/less/responsive.less
- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
- src/main/webapp/WEB-INF/jsp/users/listBeavers.jsp
- src/main/webapp/WEB-INF/tags/menu.tag
-Vista de Detalles Solicitudes altamente modificada
-Vista de Listado de Usuarios creada
> Vistas Solicitudes

- src/main/java/org/springframework/samples/petclinic/repository/SolicitudRepository.java
- src/main/java/org/springframework/samples/petclinic/service/SolicitudService.java
-Ahora cuando hay más de una solicitud no ocurre un panic cuando se comprueba si existen solicitudes pendientes o aceptadas.
> Arreglo de la función existsSolicitud

- src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
- src/main/java/org/springframework/samples/petclinic/web/EncargoController.java
- src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
Añadida comprobación para usuarios no autentificados.
> Updated PerfilController

- src/main/webapp/WEB-INF/jsp/encargos/encargosDetails.jsp
Se ha retirado el botón de eliminación de encargo.
> Eliminar Encargo

- src/main/less/petclinic.less
- src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
Añadiendo los cambios del listado de Solicitudes
> Añadiendo los cambios del Listado

- readme.md
- src/main/resources/db/hsqldb/data.sql
-Admin user added.
-Codacy coverage badge added.
> New admin user

- info.yml
https://github.com/ivanhr3/BeavArts/issues/80
Info.yml añadido para poder usar la herramienta Governify.
> Info yml para Governify

- src/main/java/org/springframework/samples/petclinic/model/Especialidad.java
- src/main/java/org/springframework/samples/petclinic/web/AnuncioController.java
- src/main/java/org/springframework/samples/petclinic/web/UserController.java
- src/main/resources/db/hsqldb/data.sql
- src/test/java/org/springframework/samples/petclinic/model/AnuncioValidatorTests.java
- src/test/java/org/springframework/samples/petclinic/service/AnuncioServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/BeaverServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/PortfolioServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/SolicitudServiceTests.java
- src/test/java/org/springframework/samples/petclinic/web/BeaverControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
#98
Se han añadido las credenciales de los usuarios piloto al arranque por defecto de la aplicación para su acceso en la fase de pruebas.
Dada una incompatibilidad con las tildes de las especialidades que tienen, se ha refactorizado el código necesario para eliminarla de controladores y tests.
> Poblado de BBDD con los datos de usuarios piloto

- .travis.yml
- src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
https://github.com/ivanhr3/BeavArts/issues/102
Arreglando los tests que se han añadido mal, se ha cambiado el enumerado que se declaraba por el equivalente actual.
> Fixtestanuncios issue#102

- src/main/java/org/springframework/samples/petclinic/service/UserService.java
Closes #137 
Cambio de última hora.
> Cambio URL confirmación

- src/test/java/org/springframework/samples/petclinic/service/AnuncioServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/BeaverServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/FacturaServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/SolicitudServiceTests.java
- src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/BeaverControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/EncargoControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Aumentado el coverage de los tests de controlador y servicio. Para ello se han añadido diversos tests que comprueban ciertos elementos que quedaban sin testear.
> Aumento del coverage issue#141

- src/main/java/org/springframework/samples/petclinic/service/ValoracionService.java
Solucionado el bug por el que las valoraciones se creaban por triplicado.
> Hotfix en creacion de valoraciones

- src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
Closes #151 
Arregla:
-Ya no se puede pulsar el botón de submit de registro tras haberlo pulsado una vez de forma exitosa.
-Ahora los campos Nombre y Apellidos son required, no sé porque no había mensaje de error antes.
> Bugfix registro issue#151

- src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
-El botón de Valorar se ha ocultado para que salga cuando está logueado
> HOTFIX 02 - Redireccion al valorar a un usuario sin logearse issue#153

- src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/aceptarSuccess.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/creationForm.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/rechazarSuccess.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
- Cambiado idioma de mensajes de transacciones al español.
- También se han modificado algunas vistas de solicitud, pero son cambios
menores.
>  HOTFIX-05-Mensaje-al-pagar-issue#155

- src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
-Se ha ocultado uno de los botones de eliminar anuncio para que este
aparezca cuando el usuario no es admin
> HOTFIX 03 – Admin muestra un anuncio que ha creado el mismo issue#154

- src/main/java/org/springframework/samples/petclinic/model/Anuncio.java
- src/main/java/org/springframework/samples/petclinic/model/Encargo.java
- src/main/java/org/springframework/samples/petclinic/model/User.java
Closes #172 
Eliminadas la opción Orphan Removal de las relaciones de algunas entidades.
> Eliminadas relaciones con OrphanRemoval

- src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/creationForm.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
Closes #162 
-Añadida validación javascript para botón de PayPal a la hora de crear encargos.
> Hotfix11pagos issue#162

- src/main/java/org/springframework/samples/petclinic/service/AnuncioService.java
- src/main/java/org/springframework/samples/petclinic/service/EncargoService.java
Close #175 
Los encargos y anuncios ya no se crean doble.
> Creacion Doble eliminada

- src/main/java/org/springframework/samples/petclinic/model/Factura.java
- src/main/java/org/springframework/samples/petclinic/web/FacturaController.java
- src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
- src/main/webapp/WEB-INF/jsp/facturas/facturasDetails.jsp
- src/main/webapp/WEB-INF/jsp/facturas/listFacturas.jsp
- src/test/java/org/springframework/samples/petclinic/service/FacturaServiceTests.java
- src/test/java/org/springframework/samples/petclinic/web/FacturaControllerTests.java
- Se ha añadido el estado de factura, precio con comision y la comision en los detalles de la facturas.
- Se ha añadido un botón para finalizar la factura.
> Estado factura issue#168

- src/main/java/org/springframework/samples/petclinic/model/Solicitud.java
- src/main/webapp/WEB-INF/jsp/anuncios/listAnuncios.jsp
- src/main/webapp/WEB-INF/jsp/encargos/listEncargos.jsp
Closes #177 
-Botones de borrado para el Admin añadido a los modals
-Error por el que el borrado no funcionaba solucionado
POR FAVOR, PROBAR ESTE PR ANTES DE ACEPTARLO.
> Hotfix13borradoadmin issue#177

- src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
- src/main/java/org/springframework/samples/petclinic/web/ValoracionController.java
- src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
Errores del perfil de un beaver corregidos.
> Fix Perfil Beaver

- src/main/java/org/springframework/samples/petclinic/model/Factura.java
- src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/facturas/facturasDetails.jsp
- src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
- src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Closes #169 
PROBAR ANTES DE MERGEAR.
> Confirmacion de Recepcion de Encargo

- src/main/resources/application-mysql-travis.properties
- src/main/resources/application.properties
-Acortados los logs de tests
Closes #189
> Logs acortados

- src/main/java/org/springframework/samples/petclinic/model/Factura.java
- src/main/java/org/springframework/samples/petclinic/model/Solicitud.java
- src/main/java/org/springframework/samples/petclinic/repository/SolicitudRepository.java
- src/main/java/org/springframework/samples/petclinic/service/FacturaService.java
- src/main/java/org/springframework/samples/petclinic/service/SolicitudService.java
- src/main/java/org/springframework/samples/petclinic/service/UserService.java
- src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
- src/main/java/org/springframework/samples/petclinic/web/UserController.java
- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
- src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
Closes #188 
Evitar el borrado de las facturas
> Facturaspersistence issue#188

- src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
Se ha corregido un panic que surgía al entrar en el perfil de un usuario con valoraciones sin estar logueado
> Fix panic in Perfil Beaver without login

- src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
Se ha corregio la URL en el listado de solicitudes, cuando se envia un encargo el user que mostraba era el que habia realizado la solicitud, no el que habia creado el encargo.
> HOTFIX21 - Fix URL en listado de solicitudes issue #205

- Procfile
- src/main/resources/application-mysql.properties
- src/main/resources/application.properties
> Base datos remota issue#209

- Procfile
- src/main/resources/application-mysql.properties
Reverts ivanhr3/BeavArts#210
Estos cambios no funcionan adecuadamente.
Closes #209
> Revert "Base datos remota issue#209"

- src/main/java/org/springframework/samples/petclinic/service/AuthoritiesService.java
- src/main/java/org/springframework/samples/petclinic/service/UserService.java
> Changed Authorities dependencies

- src/main/java/org/springframework/samples/petclinic/web/UserController.java
Closes #225 
Cambiado el número minimo de carácteres de un username de 8 a 4.
> Cambiado numero minimo caracteres de usuario

- src/main/webapp/WEB-INF/jsp/encargos/createEncargosForm.jsp
Closes #220 
Ahora durante la edición de un encargo, el botón de Submit se esconde cuando se intenta actualizar un encargo que se encuentra disponible para usar el mismo estado. (Editar y no cambiar nada si está disponible). [RECOMENDABLE PROBARLO PRIMERO]
> Hotfix 43 - Esconder Boton

- src/main/java/org/springframework/samples/petclinic/web/UserController.java
- src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
> Fix mantener datos en el form de registro cuando hay algun error

- src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
- src/main/webapp/WEB-INF/jsp/users/editarEspecialidades.jsp
> Selección de especialidades más intuitivo

- src/main/less/petclinic.scss
- src/main/resources/messages/messages.properties
- src/main/webapp/WEB-INF/jsp/encargos/createEncargosForm.jsp
- src/main/webapp/WEB-INF/jsp/welcome.jsp
- src/main/webapp/WEB-INF/tags/footer.tag
- src/main/webapp/WEB-INF/tags/layout.tag
- Botón "Go Back" añadido a Edición Encargos
- Iconos ¿Arreglados? Seguramente
closes #239
> Hotfix49 issue#239
